### ISSUE TITLE
apiプロキシを経由するエンドポイントを限定的にして、一般的なものは別のaccessKeyで直接apiアクセスするようにする(検討)

### ISSUE THREAD

**Issue by marihachi** [frost-social/Frost-Web#21]
迷ってる

**Comment by otofune** [comment]
Special系の権限はユーザーメイクのアプリケーションにはどうせ付与できないのだから、Special系の処理だけ挟むようにするのはありじゃないですか
あと `X-Application-Key` で権限判断するの辞めて `X-Access-Key` からアプリケーション逆引きしてそれで権限を割り出すというようにすればアプリケーションキーも割れないし良いんじゃない
もしくは謹製のアプリケーションだけはリクエスト方法変えるか

**Comment by marihachi** [comment]
Special系の処理だけ挟むっていうのはあり

**Comment by marihachi** [comment]
もう一度考え直したけど
appKeyを廃止まではしなくても、連携時にだけappKey要求して、その後のapiリクエストではaccessKeyだけを要求するっていうのもアリか

**Comment by marihachi** [comment]
検討の結果をまとめたのでclose -> #39
