### ISSUE TITLE
フロントのSPA化に関する課題

### ISSUE THREAD

**Issue by marihachi** [frost-social/Frost-Web#39]
## 現状
- フロントをSPA化したい
  - スタンドアロンに近づいていくのでページレンダリング時やその他のほとんどのapiアクセスがwebサーバを通さずに直接フロント上で行っていく必要があるだろう
- フロントがappkey/accessKeyの代わりにセッションを介してapiを呼び出している(streamingProxy)ので、余計なサーバリソースが必要になっている
## 今後
- [x] SPA化 #36 
- [ ] StreamingProxyを廃止して直接apiリクエストさせるようにする #37 
  - [ ] [API] appKeyを連携時にだけ要求するように Frost-Dev/Frost-API#70 
  - [ ] [API] AccessKey毎に個別の権限を設定可能にする Frost-Dev/Frost-API#88
- [ ] 内部APIはストリーミング上から呼び出せるように(特殊権限を必要とする操作にはreCAPTCHAトークンを要求) #18

**Comment by marihachi** [comment]
内部APIとAPIでwebsocketのストリームが2本になるなあ

**Comment by otofune** [comment]
内部API、ちゃんと制限かければよくない？っていう

**Comment by marihachi** [comment]
@otofune  制限と言うと？

**Comment by otofune** [comment]
@marihachi どんな構想してるのか知らないがせっかく公式アプリケーション向けtokenがあった気がするので1本で制限かければ良くない？っていう

**Comment by marihachi** [comment]
@otofune 内部APIって呼んでいるのは、フロント向けにいくつかのAPI操作を組み合わせたりした応用的なAPI(`POST /session/register` とか)で、これは**Webサーバから提供される**よ。
だから APIサーバからの通常のAPIのストリーム と Webサーバからのストリーム で2本になるよなあって考えてた

**Comment by marihachi** [comment]
制限の意味がまだ良く分かってないけど..
それが「API側でWebサーバからのリクエストかどうかを確認して、Webサーバなら特殊権限操作を許すっていうように利用可能な権限に変化を持たせる」って意味なら、美しくないのでダメだなあ

**Comment by marihachi** [comment]
@otofune 制限の意味がまだ良く分かってないけど..
それが「WebサーバからAPIにリクエストされたかどうかで、Webサーバなら特殊権限の利用を許すというように利用可能な権限に制限を持たせる」って意味なら、美しくないのでダメだなあ

**Comment by otofune** [comment]
Webの特殊APIがいるかはさておき、送信先が違うならば2本になるのは仕方なさそう。API側に特殊エンドポイントがあるならスコープ設けてトークンで制限かけるのが最も賢い、と思ったという反応なので・・・

**Comment by marihachi** [comment]
なるほどね

**Comment by marihachi** [comment]
OAuth2対応によって、ここで出てきていた問題も解消できそうなのでここは閉じます
