### ISSUE TITLE
改行できない

### ISSUE THREAD

**Issue by otofune** [frost-social/Frost-Web#40]
Enterで送信されてしまうため

**Comment by marihachi** [comment]
自分の環境だと、送信されないので直しようがない
キーの判定は以下の1行でやってるので、いじるならここ
https://github.com/Frost-Dev/Frost-Web/blob/1305fc97463604628f7ad32cc91c2ca4fe0eff5f/src/client/tags/frost-create-status-form.tag#L45

**Comment by marihachi** [comment]
それが発生した環境を教えてほしい

**Comment by otofune** [comment]
Arch LinuxとChromeだけれど、バージョンが今出先でわからないのであとで書きます

**Comment by marihachi** [comment]
OSによってはキーコードが異なってるかもしれないね

**Comment by marihachi** [comment]
でも、Enterだけでsubmitされるのは、そういう問題でもないかもしれない

**Comment by marihachi** [comment]
少しコードを改善した
https://github.com/Frost-Dev/Frost-Web/commit/50125e77c1f13a970d73875ea6e98e685db15f68

テストコードを用意したから、改善されたかどうかを確認してほしい
https://jsfiddle.net/693r3ak5/1/

**Comment by otofune** [comment]
改善されていない。このテストコードを見る限り入力を保持した結果で送信出来るか見るのに送信後にリセットしていないので何かしらの新規キーが押された段階で送信されている。また、KeyboardEventには `metaKey` プロパティと `CtrlKey` プロパティ (どちらも押されている時にtrueを取る) が存在するので (参考: [KeyBoard Event - Web APIs | MDN](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent)) 現状のような面倒なことをしなくても済むかと、実装を今から用意するので是非確認してほしい。

**Comment by marihachi** [comment]
入力テキストのリセットはcreateStatus内のthis.clear();で行っているよ
firstTimeの判定がないと、keydownイベント押されてる間複数回発生しない？

**Comment by otofune** [comment]
入力テキストではなく、押されたキーを保持するオブジェクトのことです

**Comment by marihachi** [comment]
keyUp発生時にそれぞれリセットされない？

**Comment by otofune** [comment]
本当だ。すまない、それだと思ったもんで…何故動かないのかにまた戻ってしまった

**Comment by otofune** [comment]
複数回発生するのは送信を実行するときにlockを作るほうがスッキリしそうかな

**Comment by marihachi** [comment]
e.ctrlKey、e.metaKeyを使うっていうのは賛成
lockってどういう処理だろう

**Comment by otofune** [comment]
「送信処理を実行するときに `this.lock = true` しておき、`this.lock` が有効である間は入力枠をdisableにしておく。送信処理が完了・失敗したら `this.lock = false` にする。」という処理を想像している

**Comment by marihachi** [comment]
失敗時はthis.clear()されないので、キーが長押しされてれば再試行が行われてしまいそう

**Comment by otofune** [comment]
失敗時は再試行してもいいんじゃないか？文字数が多すぎて、などは元々弾かれてるわけだし経路とかの問題か、制限に引っかかってるだけだろうから。再試行させたくないなら文字入力があったらlock解除という処理追加してもいいかもしれない

**Comment by marihachi** [comment]
ユーザーの一度の押下で再試行されるのって単純にキモくない？

**Comment by otofune** [comment]
そうか？押しっぱなしにしてるなら当然の動作な気がする

**Comment by marihachi** [comment]
うーん...

**Comment by marihachi** [comment]
それはつらい

**Comment by marihachi** [comment]
formを使うことを止めるか
submitの概念がなくなるので、流石にこれなら直るんじゃないかな
onclickに置き換えよう

**Comment by otofune** [comment]
formではなく判定コードでは…？と思っているんだが

**Comment by otofune** [comment]
試してみても良いかも知れないけど、formは使いたくないですか？

**Comment by marihachi** [comment]
見た目上あったほうがいいけどね
Enterの入力とsubmitイベントが紐付いてるのかも

**Comment by marihachi** [comment]
環境によって(知らん)

**Comment by otofune** [comment]
NumpadEnterでもされた。そもそもNumpadEnterはFrostは対応してないからそうかもしれないが、それにしても一回Ctrl+Enterで送信してからしか現象は起きないので絶対どっかおかしいと思うんだよな。一律で起きるならまだわかるが

**Comment by marihachi** [comment]
なに、そうなの？

**Comment by otofune** [comment]
さっきもしかしたらと思って試したらテストコードでも本番でも再現した、間違いない

**Comment by marihachi** [comment]
Ctrl Enterのコードを無効化してみた
https://jsfiddle.net/693r3ak5/3/

これだとどうなる？

**Comment by otofune** [comment]
当然っぽいが起きない

**Comment by marihachi** [comment]
んー.. どこがおかしいんだろ

**Comment by otofune** [comment]
ControlLeft、どうもkeyUpイベントに流れてきていなさそうじゃないですか？

**Comment by otofune** [comment]
これは一度Ctrl + Enterした後の単体でのKeyB入力の様子です
![image](https://user-images.githubusercontent.com/15062473/29729608-cd219fd2-8a17-11e7-8ae1-cd6f198fbe7c.png)

**Comment by marihachi** [comment]
えーなにそれ :cry:

**Comment by otofune** [comment]
残念ながら破綻というかたちです

**Comment by otofune** [comment]
最後に原因が特定できたがなにも分からなかった時を考えるとまだよかったかなというところです。対策どうしますか？

**Comment by otofune** [comment]
僕はとりあえず今出してるPRにロック機構を追加してみようかなと思います

**Comment by marihachi** [comment]
対策どうしようかね

**Comment by otofune** [comment]
うーん。かなり面倒そうなんだよな。とりあえずロック機構は出来たので #42 を1つの提案として確認してみて欲しい。

**Comment by marihachi** [comment]
マージしたよ
とりあえず音船のコードをベースに考えていくよ

**Comment by otofune** [comment]
ありがとう、実際に動かしてみて修正されたと確認できたらクローズしよう

**Comment by marihachi** [comment]
あーでも本番環境へのデプロイはもうちょっと先かもだから模擬コードで

**Comment by marihachi** [comment]
https://jsfiddle.net/693r3ak5/4/

**Comment by marihachi** [comment]
あ間違えた

**Comment by marihachi** [comment]
success: https://jsfiddle.net/693r3ak5/6/
failed: https://jsfiddle.net/693r3ak5/5/
はい

**Comment by marihachi** [comment]
良い挙動になった ありがとね :+1:

**Comment by otofune** [comment]
failed はこれっぽい https://jsfiddle.net/693r3ak5/7/

**Comment by marihachi** [comment]
確かに
模擬コードの時点では動きそう？

**Comment by otofune** [comment]
動きそう。模擬コードでの根拠で良いならクローズできるかな

**Comment by marihachi** [comment]
本質的には同じだから大丈夫だと思うし、クローズするね
