### ISSUE TITLE
frost-post-statusタグのcompileTextの処理を改善する

### ISSUE THREAD

**Issue by marihachi** [frost-social/Frost-Web#63]
今は置換で無理やり済ましてる処理も、もう少しまともな書き方がある気がするんだよな

**Comment by acid-chicken** [comment]
配列作ってreduceで回した方がきれい

**Comment by marihachi** [comment]
なるほどね、一般的にはそんな感じなのかな

**Comment by acid-chicken** [comment]
あくまでぼくならそうするだけなので、一般的かどうかはなんとも言えない

**Comment by marihachi** [comment]
デカくなったけど随分と改善された
https://github.com/Frost-Dev/Frost-Web/commit/122f4cf8b0dc65f2ec39927298802fa7fd460bba
https://github.com/Frost-Dev/Frost-Web/blob/122f4cf8b0dc65f2ec39927298802fa7fd460bba/src/client/tags/frost-post-status.tag#L84-L186
