### ISSUE TITLE
Suggestion: Add general timeline link to global-nav

### ISSUE THREAD

**Issue by JohnTitor** [frost-social/Frost-Web#72]
Frost is so coooooool!!!
However, it isn't user-friendly you cannot intuitively go to general timeline after signing in.
So I suggest to add general timeline link to global-nav.
I came up with the code like this for this suggestion, is it right?

```
<li class={ active: activeId == (login ? 'home' : 'entrance') }>
	<a href='/'>{ login ? 'Home' : 'Entrance' }</a>
</li>
<li if={ login } class={ active: activeId == 'home' }>
	<a href='/general'>General</a>
</li>
<li if={ login } class={ active: activeId == 'userlist' }>
	<a href='/userlist'>UserList</a>
</li>
```

**Comment by marihachi** [comment]
@diplozoon issueありがとう！
一応、General timeline機能はFrostとして隠し機能(イースターエッグ)的な位置づけなので、グローバルナビにリンクを追加していません。
この機能を知っているあなたはFrostをよく知っていますね！

また、コミュニティ全体にポストが公開されることは個人的にはあまり良いと思っていません。
なのでもしかしたら将来的にGeneral timeline機能は削除されるかも知れません。
できれば、General timelineに関してはオマケ機能のような認識を持ってもらえるとうれしいです。

**Comment by JohnTitor** [comment]
なるほど！そういう意図があったのですね
そうとは知らず出過ぎた提案をしてしまいました……
Frostの方針について理解が深まりました
そういうことであるならば、このissueはふさわしくないので閉じようと思います、対応ありがとう！
